language: python
sudo: false
env:
  global:
    - PYTHON=python3
matrix:
  include:
    - name: "Python: 3.5"
      os: linux
      python: "3.5"
    - name: "Python: 3.6"
      os: linux
      python: "3.6"
    - name: "Python: 3.7"
      os: linux
      dist: xenial
      python: "3.7"
    - name: "Python"
      os: osx
      language: generic
      before_install:
        - wget --no-verbose -O python.pkg "$PYTHON_PKG_URL"
        - sudo installer -pkg python.pkg -target /
        - rm python.pkg
    - name: "Python: 3.x"
      os: windows
      language: shell
      before_install:
        - choco install python3 --version=$PYTHON_VERSION_WINDOWS --params "/InstallDir:C:\\Python"
      env:
        - PYTHON=/c/Python/python.exe
install:
  - $PYTHON -m pip install --upgrade . coverage mypy
script:
  - $PYTHON -m coverage run -m unittest -b
  - $PYTHON -m mypy -p stringly --strict
after_success:
  - $PYTHON -m coverage xml -i
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
# vim: ts=2:sts=2:sw=2:et
